// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_sdram.h for the primary calling header

#ifndef VERILATED_VTB_SDRAM_R3900__CZ2_H_
#define VERILATED_VTB_SDRAM_R3900__CZ2_H_  // guard

#include "verilated.h"


class Vtb_sdram__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_sdram_r3900__Cz2 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst_n,0,0);
        VL_OUT8(__PVT__ibus_req,0,0);
        VL_OUT8(__PVT__ibus_cached,0,0);
        VL_IN8(__PVT__ibus_ack,0,0);
        VL_IN8(__PVT__ibus_err,0,0);
        VL_OUT8(__PVT__dbus_req,0,0);
        VL_OUT8(__PVT__dbus_cached,0,0);
        VL_OUT8(__PVT__dbus_we,0,0);
        VL_OUT8(__PVT__dbus_be,3,0);
        VL_IN8(__PVT__dbus_ack,0,0);
        VL_IN8(__PVT__dbus_err,0,0);
        VL_IN8(__PVT__irq_in,5,0);
        VL_OUT8(__PVT__cache_op,0,0);
        VL_OUT8(__PVT__retire_valid,0,0);
        CData/*0:0*/ __PVT__id_v;
        CData/*0:0*/ __PVT__id_ds;
        CData/*4:0*/ __PVT__id_exc_code;
        CData/*0:0*/ __PVT__id_exc_v;
        CData/*0:0*/ __PVT__id_exc_bad_v;
        CData/*0:0*/ __PVT__ex_v;
        CData/*0:0*/ __PVT__ex_ds;
        CData/*0:0*/ __PVT__ex_exc_v;
        CData/*4:0*/ __PVT__ex_exc_code;
        CData/*0:0*/ __PVT__ex_exc_bad_v;
        CData/*0:0*/ __PVT__ex_exc_ret;
        CData/*0:0*/ __PVT__me_v;
        CData/*0:0*/ __PVT__me_hilo_we;
        CData/*0:0*/ __PVT__me_ds;
        CData/*0:0*/ __PVT__me_exc_v;
        CData/*4:0*/ __PVT__me_exc_code;
        CData/*0:0*/ __PVT__me_exc_bad_v;
        CData/*0:0*/ __PVT__me_exc_ret;
        CData/*0:0*/ __PVT__wb_v;
        CData/*4:0*/ __PVT__wb_wa;
        CData/*0:0*/ __PVT__wb_we;
        CData/*0:0*/ __PVT__wb_hilo_we;
        CData/*0:0*/ __PVT__wb_cp0_we;
        CData/*4:0*/ __PVT__wb_cp0_a;
        CData/*0:0*/ __PVT__wb_cache;
        CData/*0:0*/ __PVT__exc_flush;
        CData/*0:0*/ __PVT__adv_mem;
        CData/*0:0*/ __PVT__adv_ex;
        CData/*0:0*/ __PVT__adv_id;
        CData/*0:0*/ __PVT__redir_v;
        CData/*0:0*/ __PVT__id_redirect;
        CData/*0:0*/ __PVT__fetch_ok;
        CData/*4:0*/ __PVT__ex_wa;
        CData/*4:0*/ __PVT__me_wa;
        CData/*0:0*/ __PVT__id_taken;
        CData/*0:0*/ __PVT__load_use;
        CData/*0:0*/ __PVT__branch_load_use;
        CData/*0:0*/ __PVT__special_inflight;
        CData/*0:0*/ __PVT__special_hazard;
        CData/*0:0*/ __PVT__cp0_write_inflight;
        CData/*0:0*/ __PVT__id_take_irq;
        CData/*5:0*/ __PVT__md_count;
        CData/*0:0*/ __PVT__md_run;
        CData/*0:0*/ __PVT__md_neg_q;
        CData/*0:0*/ __PVT__md_neg_r;
        CData/*0:0*/ __PVT__md_skip;
        CData/*0:0*/ __PVT__ex_is_div;
        CData/*0:0*/ __PVT__ex_sys;
        CData/*0:0*/ __PVT__ex_bp;
    };
    struct {
        CData/*0:0*/ __PVT__ex_exc_out_v;
        CData/*4:0*/ __PVT__ex_exc_out_code;
        CData/*0:0*/ __PVT__ex_exc_out_badv;
        CData/*0:0*/ __PVT__ex_exc_out_ret;
        CData/*0:0*/ __PVT__me_phase;
        CData/*0:0*/ __PVT__me_needs_mem;
        CData/*0:0*/ __PVT__me_last_beat;
        CData/*3:0*/ __PVT__me_be;
        CData/*0:0*/ __PVT__me_exc_out_v;
        CData/*4:0*/ __PVT__me_exc_out_code;
        CData/*0:0*/ __PVT__me_exc_out_badv;
        CData/*0:0*/ __PVT__me_exc_out_ret;
        CData/*0:0*/ __PVT__rt_v;
        CData/*0:0*/ __VdfgExtracted_h84f92045__0;
        CData/*4:0*/ __VdfgExtracted_h9d8030ea__0;
        CData/*0:0*/ __VdfgTmp_hcfa842a8__0;
        CData/*0:0*/ __VdfgTmp_hc5c1aa8c__0;
        CData/*0:0*/ __VdfgTmp_h42ed6c05__0;
        CData/*0:0*/ __Vfunc_writes_gpr__5__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__6__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__7__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__8__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__9__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__10__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__11__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__12__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__13__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__14__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__15__Vfuncout;
        CData/*0:0*/ __Vfunc_writes_gpr__16__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__17__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__18__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__19__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__20__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__21__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__22__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__23__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__24__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__25__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__26__Vfuncout;
        CData/*0:0*/ __Vfunc_is_load__29__Vfuncout;
        CData/*0:0*/ __Vfunc_is_load__30__Vfuncout;
        CData/*0:0*/ __Vfunc_reads_rs__31__Vfuncout;
        CData/*0:0*/ __Vfunc_reads_rt__32__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__33__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__34__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__35__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__36__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__37__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__38__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__39__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__40__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__41__Vfuncout;
        CData/*0:0*/ __Vfunc_writes_gpr__42__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__43__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__44__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__45__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__46__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__47__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__48__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__49__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__50__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__51__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__52__Vfuncout;
    };
    struct {
        CData/*0:0*/ __Vfunc_is_load__53__Vfuncout;
        CData/*0:0*/ __Vfunc_is_branch__54__Vfuncout;
        CData/*0:0*/ __Vfunc_writes_gpr__55__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__56__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__57__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__58__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__59__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__60__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__61__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__62__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__63__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__64__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__65__Vfuncout;
        CData/*0:0*/ __Vfunc_writes_cp0_or_hilo__66__Vfuncout;
        CData/*0:0*/ __Vfunc_writes_cp0_or_hilo__67__Vfuncout;
        CData/*0:0*/ __Vfunc_touches_cp0__68__Vfuncout;
        CData/*0:0*/ __Vfunc_touches_hilo__69__Vfuncout;
        CData/*0:0*/ __Vfunc_touches_cp0__70__Vfuncout;
        CData/*0:0*/ __Vfunc_touches_cp0__71__Vfuncout;
        CData/*0:0*/ __Vfunc_is_mem__72__Vfuncout;
        CData/*0:0*/ __Vfunc_is_load__73__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__74__Vfuncout;
        CData/*0:0*/ __Vfunc_is_rmw__75__Vfuncout;
        CData/*0:0*/ __Vfunc_is_rmw__76__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__77__Vfuncout;
        CData/*0:0*/ __Vfunc_is_store__99__Vfuncout;
        VL_OUT(__PVT__ibus_addr,31,0);
        VL_OUT(__PVT__ibus_addr_la,31,0);
        VL_IN(__PVT__ibus_rdata,31,0);
        VL_OUT(__PVT__dbus_addr,31,0);
        VL_OUT(__PVT__dbus_addr_la,31,0);
        VL_OUT(__PVT__dbus_wdata,31,0);
        VL_IN(__PVT__dbus_rdata,31,0);
        VL_OUT(__PVT__cache_op_addr,31,0);
        VL_OUT(__PVT__retire_pc,31,0);
        VL_OUT(__PVT__retire_insn,31,0);
        VL_OUT(__PVT__retire_next_pc,31,0);
        IData/*31:0*/ hi;
        IData/*31:0*/ lo;
        IData/*31:0*/ __PVT__id_pc;
        IData/*31:0*/ __PVT__id_insn;
        IData/*31:0*/ __PVT__id_exc_bad;
        IData/*31:0*/ __PVT__ex_pc;
        IData/*31:0*/ __PVT__ex_insn;
        IData/*31:0*/ __PVT__ex_next_pc;
        IData/*31:0*/ __PVT__ex_rs_raw;
        IData/*31:0*/ __PVT__ex_rt_raw;
        IData/*31:0*/ __PVT__ex_exc_bad;
        IData/*31:0*/ __PVT__me_pc;
        IData/*31:0*/ __PVT__me_insn;
        IData/*31:0*/ __PVT__me_next_pc;
        IData/*31:0*/ __PVT__me_result;
        IData/*31:0*/ __PVT__me_rt;
        IData/*31:0*/ __PVT__me_va;
        IData/*31:0*/ __PVT__me_hi;
        IData/*31:0*/ __PVT__me_lo;
        IData/*31:0*/ __PVT__me_exc_bad;
        IData/*31:0*/ __PVT__wb_pc;
        IData/*31:0*/ __PVT__wb_insn;
        IData/*31:0*/ __PVT__wb_next_pc;
        IData/*31:0*/ __PVT__wb_value;
        IData/*31:0*/ __PVT__wb_hi;
        IData/*31:0*/ __PVT__wb_lo;
        IData/*31:0*/ __PVT__wb_cp0_d;
    };
    struct {
        IData/*31:0*/ __PVT__cause_live;
        IData/*31:0*/ __PVT__fpc;
        IData/*31:0*/ __PVT__redir_pc;
        IData/*31:0*/ __PVT__fpc_nxt;
        IData/*31:0*/ __PVT__i_id;
        IData/*31:0*/ __PVT__a_next_pc;
        IData/*31:0*/ __PVT__id_s;
        IData/*31:0*/ __PVT__id_t;
        IData/*31:0*/ __PVT__id_tgt;
        IData/*31:0*/ __PVT__id_next_pc;
        IData/*31:0*/ __PVT__i_ex;
        IData/*31:0*/ __PVT__ex_simm;
        IData/*31:0*/ __PVT__s;
        IData/*31:0*/ __PVT__t;
        IData/*31:0*/ __PVT__addi_r;
        IData/*31:0*/ __PVT__alu;
        IData/*31:0*/ __PVT__md_d;
        IData/*31:0*/ __PVT__md_fix_hi;
        IData/*31:0*/ __PVT__md_fix_lo;
        IData/*31:0*/ __PVT__s_mag;
        IData/*31:0*/ __PVT__t_mag;
        IData/*31:0*/ __PVT__div_q;
        IData/*31:0*/ __PVT__div_r;
        IData/*31:0*/ __PVT__ex_exc_out_bad;
        IData/*31:0*/ __PVT__i_me;
        IData/*31:0*/ __PVT__me_rmw_word;
        IData/*31:0*/ __PVT__store_word;
        IData/*31:0*/ __PVT__load_value;
        IData/*31:0*/ __PVT__me_exc_out_bad;
        IData/*31:0*/ __PVT__exc_vector;
        IData/*31:0*/ __PVT__rt_pc;
        IData/*31:0*/ __PVT__rt_insn;
        IData/*31:0*/ __PVT__rt_next_pc;
        IData/*31:0*/ __Vfunc_phys__2__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__2__va;
        IData/*31:0*/ __Vfunc_phys__3__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__3__va;
        IData/*31:0*/ __Vfunc_phys__4__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__4__va;
        IData/*31:0*/ __Vfunc_writes_gpr__5__i;
        IData/*31:0*/ __Vfunc_is_store__6__i;
        IData/*31:0*/ __Vfunc_is_store__7__i;
        IData/*31:0*/ __Vfunc_is_store__8__i;
        IData/*31:0*/ __Vfunc_is_store__9__i;
        IData/*31:0*/ __Vfunc_is_store__10__i;
        IData/*31:0*/ __Vfunc_is_store__11__i;
        IData/*31:0*/ __Vfunc_is_store__12__i;
        IData/*31:0*/ __Vfunc_is_store__13__i;
        IData/*31:0*/ __Vfunc_is_store__14__i;
        IData/*31:0*/ __Vfunc_is_store__15__i;
        IData/*31:0*/ __Vfunc_writes_gpr__16__i;
        IData/*31:0*/ __Vfunc_is_store__17__i;
        IData/*31:0*/ __Vfunc_is_store__18__i;
        IData/*31:0*/ __Vfunc_is_store__19__i;
        IData/*31:0*/ __Vfunc_is_store__20__i;
        IData/*31:0*/ __Vfunc_is_store__21__i;
        IData/*31:0*/ __Vfunc_is_store__22__i;
        IData/*31:0*/ __Vfunc_is_store__23__i;
        IData/*31:0*/ __Vfunc_is_store__24__i;
        IData/*31:0*/ __Vfunc_is_store__25__i;
        IData/*31:0*/ __Vfunc_is_store__26__i;
        IData/*31:0*/ __Vfunc_is_load__29__i;
        IData/*31:0*/ __Vfunc_is_load__30__i;
        IData/*31:0*/ __Vfunc_reads_rs__31__i;
    };
    struct {
        IData/*31:0*/ __Vfunc_reads_rt__32__i;
        IData/*31:0*/ __Vfunc_is_store__33__i;
        IData/*31:0*/ __Vfunc_is_store__34__i;
        IData/*31:0*/ __Vfunc_is_store__35__i;
        IData/*31:0*/ __Vfunc_is_store__36__i;
        IData/*31:0*/ __Vfunc_is_store__37__i;
        IData/*31:0*/ __Vfunc_is_store__38__i;
        IData/*31:0*/ __Vfunc_is_store__39__i;
        IData/*31:0*/ __Vfunc_is_store__40__i;
        IData/*31:0*/ __Vfunc_is_store__41__i;
        IData/*31:0*/ __Vfunc_writes_gpr__42__i;
        IData/*31:0*/ __Vfunc_is_store__43__i;
        IData/*31:0*/ __Vfunc_is_store__44__i;
        IData/*31:0*/ __Vfunc_is_store__45__i;
        IData/*31:0*/ __Vfunc_is_store__46__i;
        IData/*31:0*/ __Vfunc_is_store__47__i;
        IData/*31:0*/ __Vfunc_is_store__48__i;
        IData/*31:0*/ __Vfunc_is_store__49__i;
        IData/*31:0*/ __Vfunc_is_store__50__i;
        IData/*31:0*/ __Vfunc_is_store__51__i;
        IData/*31:0*/ __Vfunc_is_store__52__i;
        IData/*31:0*/ __Vfunc_is_load__53__i;
        IData/*31:0*/ __Vfunc_is_branch__54__i;
        IData/*31:0*/ __Vfunc_writes_gpr__55__i;
        IData/*31:0*/ __Vfunc_is_store__56__i;
        IData/*31:0*/ __Vfunc_is_store__57__i;
        IData/*31:0*/ __Vfunc_is_store__58__i;
        IData/*31:0*/ __Vfunc_is_store__59__i;
        IData/*31:0*/ __Vfunc_is_store__60__i;
        IData/*31:0*/ __Vfunc_is_store__61__i;
        IData/*31:0*/ __Vfunc_is_store__62__i;
        IData/*31:0*/ __Vfunc_is_store__63__i;
        IData/*31:0*/ __Vfunc_is_store__64__i;
        IData/*31:0*/ __Vfunc_is_store__65__i;
        IData/*31:0*/ __Vfunc_writes_cp0_or_hilo__66__i;
        IData/*31:0*/ __Vfunc_writes_cp0_or_hilo__67__i;
        IData/*31:0*/ __Vfunc_touches_cp0__68__i;
        IData/*31:0*/ __Vfunc_touches_hilo__69__i;
        IData/*31:0*/ __Vfunc_touches_cp0__70__i;
        IData/*31:0*/ __Vfunc_touches_cp0__71__i;
        IData/*31:0*/ __Vfunc_is_mem__72__i;
        IData/*31:0*/ __Vfunc_is_load__73__i;
        IData/*31:0*/ __Vfunc_is_store__74__i;
        IData/*31:0*/ __Vfunc_is_rmw__75__i;
        IData/*31:0*/ __Vfunc_is_rmw__76__i;
        IData/*31:0*/ __Vfunc_is_store__77__i;
        IData/*31:0*/ __Vfunc_phys__78__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__78__va;
        IData/*31:0*/ __Vfunc_phys__81__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__81__va;
        IData/*31:0*/ __Vfunc_phys__82__Vfuncout;
        IData/*31:0*/ __Vfunc_phys__82__va;
        IData/*31:0*/ __Vfunc_is_store__99__i;
        QData/*63:0*/ insn_count;
        QData/*63:0*/ cycle_count;
        QData/*63:0*/ cache_ops;
        QData/*63:0*/ exc_count;
        QData/*63:0*/ __PVT__mul_s;
        QData/*63:0*/ __PVT__mul_u;
        QData/*63:0*/ __PVT__md_rq;
        QData/*63:0*/ __PVT__md_shifted;
        QData/*32:0*/ __PVT__md_diff;
        VlUnpacked<IData/*31:0*/, 32> regs;
        VlUnpacked<IData/*31:0*/, 32> __PVT__cp0;
    };

    // INTERNAL VARIABLES
    Vtb_sdram__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_sdram_r3900__Cz2(Vtb_sdram__Syms* symsp, const char* v__name);
    ~Vtb_sdram_r3900__Cz2();
    VL_UNCOPYABLE(Vtb_sdram_r3900__Cz2);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
